//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceDashboard.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaintenanceDashboard.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu yyyy/MM/dd.
        /// </summary>
        public static string DateTimePattern {
            get {
                return ResourceManager.GetString("DateTimePattern", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu (19|20)[0-9]{2}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01]).
        /// </summary>
        public static string DateTimeRegexPattern {
            get {
                return ResourceManager.GetString("DateTimeRegexPattern", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ^XA^FO50,40^GFA,1937,1937,13,,:::::0018Q06,001EP01E,001F8O02E,0013CO0DE,001EFN037E,001FFCM0DDE,001FFEL01E76,001D6F8K07DFE,001FBBEJ01FE7C,001D7F78I03F7BE,001F4DB4I0FFEFE,001FD6FF003979FE,001F6F7EC0F27DFE,001FE79FD1CFF8FE,001FE3FDE1FDF0FE,001FE0FF8077C0FE,001FE02F001D00FE,001FE008I0E00FE,001FEO0FE,001FAO0FE,001FEO0FE,001FEO0DE,001FEO0FE,001F6O0EE,001F8O03A,001BP01E,001CQ0E,001R02,,:::::0018E1C3F1F98102,001CE1C319818102,001DE36309818102,0017636319F98102,00136373F1818102,001067F331818102,0010641311F9F9F2,00106C [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string HeadBarcode {
            get {
                return ResourceManager.GetString("HeadBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pal[0-9]{1,3}$.
        /// </summary>
        public static string PaddleBarcodePattern {
            get {
                return ResourceManager.GetString("PaddleBarcodePattern", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu VW380 T1/T2 Base/High.
        /// </summary>
        public static string PaddleModelPattern {
            get {
                return ResourceManager.GetString("PaddleModelPattern", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ter[0-9]{1,3}$.
        /// </summary>
        public static string ThermostatBarcodePattern {
            get {
                return ResourceManager.GetString("ThermostatBarcodePattern", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Single.
        /// </summary>
        public static string ThermostatModelPattern {
            get {
                return ResourceManager.GetString("ThermostatModelPattern", resourceCulture);
            }
        }
    }
}
